Instant convert pcap to txt file
irontec/sngrep pull request #427
Opened 2023-02-01 12:23 UTC by sebk2307

add new argument: --siplify that allows to convert read .pcap file into sip messages text file without need for opening GUI.
How to use:
sngrep -I <dump.pcap> --siplify <sip-message.txt>

2023-02-06 09:15 UTC, Kaian requested changes
Thanks for the Pull request and the effort made here! I have commented with some changes.

Usually when this feature is requested, I refer to `ngrep  -Wbyline -I file.pcap`  to attain a similar result.

2023-02-06 09:15 UTC, Kaian commented on src/main.c
> +           "    -S --siplify\t save pcap to text file\n"
I prefer `-T --text` here, looks more intuitive

2023-02-06 09:15 UTC, Kaian commented on src/main.c
> +        no_interface = 1;
This is not probably required, because the only way to enter this if is through the above case, who already set this value to no_interface.

2023-02-06 09:15 UTC, Kaian commented on src/main.c
> +                siplify_outfile = optarg;
text_outfile looks more intuive

2023-02-14 09:51 UTC, merged

2023-02-14 09:51 UTC, Kaian commented
Awesome!! Thanks a lot for your contribution!

2023-02-14 09:52 UTC, sebk2307 commented
Hello, I refactored PR according you your suggestions, @Kaian.
All the Best!

2023-02-14 09:53 UTC, sebk2307 commented
@Kaian Do you know when can I expect a new software release for Fedora OS including that change?

2023-02-14 09:57 UTC, Kaian commented
I can't tell for sure. I would like to include a couple more fixes in the next release, but other projects are keeping me busy right now. 

I would like to make a release on march, but can't promise.

2023-02-14 09:59 UTC, sebk2307 commented
No rush! Thanks for the information.